title: Jijiomo Chichiomo
email: your-email@example.com
timezone: UTC
description: 
url: "."
theme: fuckoff

collections:
  media:
    title: Media
    output: false
  hooks:
    title: Hooks
    output: false

default:
- scope:
    path: ''
    type: Media
  values:
    image: 

Bio-Stats: "* Name: Jijiomo Chichiomo\n* Age: 29\n* Position: Boatswain's Mate\n* Status: Extended Vacation\n* Extra Benefits: Lazarette Cargo Space, Flexible Schedules\n* Years employed: 8\n* Place of Residence: La Noscea/Ul'dah"
Bio: "Born in Limsa Lominsa, his family has ties to the East Aldenard Trading Company dating to the foundation of the company. Members of the family were originally placed within Ul'dah, but branched out as the comapny grew. Jijiomo attended private education before coming to work for the company. Given expedited training in ship maintainance, and then recommended for placement as shipwright by Bibioko Chichioko (Logistics Administrator).\n\nOccasionally works in Ul'dah office as a company representative for smaller deals. Currently renting loft space out of one of the company's smaller Sapphire Avenue stockhouses. Dedication to the company has been awarded with proper benefits. Notable extra skills include basic Hingan, and exhaustive knowledge of aquatic life."
OOC: "* You can /tell me through Jijiomo Chichiomo@Balmung, if we're familar/rped a couple times I don't mind you asking for my discord.\n* Open to most RP (both type-wise (paragraph, line by line, etc.) and theme wise), no ERP however.\n* Rusty with RPing, so easing back into it. While on the topic, I'm still not completely familiar with all of FFXIV's lore, so if I screw up please feel free to give me a nudge."
