backend:
  name: github
  repo: crekulon/aez
  branch: main
  site_domain: wonderful-boyd-98e1c0.netlify.com

media_folder: "img/uploads"

collections:
  - name: "general"
    label: "Bio and OOC"
    files:
      - label: "Bio"
        name: "bio"
        file: "_data/bio.yml"
        fields: 
          - {label: "Bio Portrait", name: "bioimg", widget: "image"}
          - {label: "Bio", name: "bio", widget: "markdown"}
          - {label: "Stats", name: "biostats", widget: "markdown"}
      - label: "OOC"
        name: "ooc"
        file: "_data/ooc.yml"
        fields: 
          - {label: "OOC", name: "ooc", widget: "markdown"}

  - name: "media"
    label: "Media"
    folder: "_media"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "hooks"
    label: "Hooks"
    folder: "_hooks"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}